language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
install:
  - yarn
script:
  # Run backend tests
  # - npm run test

  # Build react app and copy to correct location
  - yarn build

after_success:
  # Deploy build to octopus package library
  - yarn ci:publish
